# https://docs.github.com/zh/actions/security-guides/using-secrets-in-github-actions#creating-secrets-for-a-repository
# 工作流名称
name: test secret and ssh actions
# 监听事件
on: [push]
# 工作流中的任务
jobs: 
  # job name
  SECRET-SSH-ACTIONS:
    # 运行系统
    runs-on: ubuntu-latest
    steps:
      # https://github.com/marketplace/actions/ssh-remote-commands
      - uses: appleboy/ssh-action@v1.0.3
        with:
          # https://github.com/YZhiJie/lg-backend-egg-ts/settings/secrets/actions
          # 下面的变量是在 github 仓库中添加的
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PWD }}
          # 连接失败，停止向下继续执行
          script_stop: true
          # 执行脚本
          script: |
            pwd
            ls -l
            touch secret.txt
            echo ${{ secrets.MY_SECRET }} >> secret.txt